name: "integration tests"

on: push

jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        to_test:
          - "mnist-keras keras"
          - "mnist-pytorch pytorch"
        python_version: ["3.7", "3.8", "3.9"]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      
      - name: test ${{ matrix.to_test }}
        run: .ci/tests/examples/run.sh ${{ matrix.to_test }}

      - name: print logs
        if: always()
        run: .ci/tests/examples/print_logs.sh