name: "integration tests"

on: push

jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        to_test:
          - "mnist-keras keras"
          - "mnist-pytorch pytorch"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: test ${{ matrix.to_test }}
        run: .ci/tests/examples/run.sh ${{ matrix.to_test }}